server:
  port: 80

spring:
  application:
    name: api-gateway-server


cloud:
    # 路由配置
  gateway:
      # 转发规则
    routes:
      - id: eureka-provider
        uri: http://localhost:8000/
        predicates:
          -Path:/goos/**
