server:
  port: 8000

eureka:
  instance:
    hostname: localhost #主机名
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      #defaultZone: http://eureka-server1:8761/eureka,http://eureka-server2:8762/eureka #eureka服务端地址

spring:
  application:
    name: eureka-provider